### ISSUE TITLE
"identifier" misspelled as "indentifier"

### ISSUE THREAD

**Issue by bbayles** [Comcast/scte35-js#135]
This repository has [several instances](https://github.com/Comcast/scte35-js/search?q=%22indentifier%22) of the word `identifier` misspelled as `indentifier`.

In ISO/IEC 13818-1 section 2.6.8 the name of the field is `format_identifier`.

**Comment by avhetman** [comment]
Thank you @bbayles, that is a good call out. I would approve the change if you want to make a PR fixing all of the spelling.

**Comment by bbayles** [comment]
Happy to do so, but a couple of questions:
* Could you send me the [CLA](https://github.com/Comcast/scte35-js/blob/master/CONTRIBUTING.md)?
* Could you tell me how to pick up the changes in the docs, i.e. what commands are used to generate them for this repo? (normally I'd look at what the CI system is doing, but I didn't see a CI config file here)

**Comment by avhetman** [comment]
The CLA portion should be handled for you automatically when you try to make a PR as per the CONTRIBUTING document. Please let me know if that's not the case.

I have addressed the typos in #155
