### ISSUE TITLE
[Minor]Logo/Icon image breaks on Top left corner

### ISSUE THREAD

**Issue by gowthae** [Comcast/scte35-js#153]
**Description :**
Icon image present in top let corner breaks and not displayed.

**Steps to reproduce :**

- Open the URL in chrome/Firefox browser
- Observe the icon in the top left corner of the page.

**Expected result :**
Icon should be displayed on top left corner.

**Actual Result  :**
Icon not displayed on top left corner.

**Attachment :**
Image 
<img width="1512" alt="Screenshot 2023-12-05 at 5 20 32 PM" src="https://github.com/Comcast/scte35-js/assets/51506726/2fb7a591-d8f0-4efc-bbad-9c85d1ffcf3e">

**Comment by avhetman** [comment]
Thank you for bringing this to my attention, I am addressing this in #155
