### ISSUE TITLE
Package configuration for import

### ISSUE THREAD

**Issue by bbert** [Comcast/scte35-js#21]
The package.json has incorrect main property or index.js file is missing, thus it is not possible to import module using npm.

Also types declaration is missing in package.json.

**Comment by estobbart** [comment]
Thanks @bbert. Interested in contributing? If not, no worries, we can fix this up if you want.

**Comment by bbert** [comment]
Not for the moment. It's preferable you fix it, since I simply failed to build your project...
And thus this would avoid me to sign the CLA just for project configuration.

**Comment by moish83** [comment]
@estobbart has this been delivered to an official version?
The latest is currently 0.2.5 and it doesn't have this fix in it.
