### ISSUE TITLE
Cannot install npm (case sensitive issues)

### ISSUE THREAD

**Issue by eyahalomi** [Comcast/scte35-js#49]
Guys, I am using latest version (2.10).
Package.json
"main": "build/SCTE35.js", but in build folder the file is "scte35.js". In windows that will work however in Linux env I had to rename it

**Comment by avhetman** [comment]
Thanks for reporting this @eyahalomi, I will resolve this shortly.

**Comment by avhetman** [comment]
Please get the latest release that contains the fix, version 0.2.11

**Comment by eyahalomi** [comment]
Awesome!
Thank you
